# Generated by Django 3.1.1 on 2020-09-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vac', '0002_remove_company_employee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
