# Generated by Django 3.1.1 on 2020-09-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vac', '0003_company_employee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
