# Generated by Django 3.1.1 on 2020-09-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vac', '0004_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
