# Generated by Django 3.1.1 on 2020-09-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vac', '0009_auto_20200919_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
