# Generated by Django 3.1.1 on 2020-09-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vac', '0013_company_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='whritten_username',
            new_name='written_username',
        ),
    ]
