# Generated by Django 3.1.1 on 2020-09-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vac', '0014_auto_20200920_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
