# Generated by Django 3.1.1 on 2020-09-20 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_vac', '0016_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Applications',
        ),
    ]
