# Generated by Django 3.1.1 on 2020-09-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vac', '0017_auto_20200920_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
