# Generated by Django 3.1.1 on 2020-09-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vac', '0020_auto_20200920_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
